# Generated by Django 2.1.7 on 2019-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Email',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Issue',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Query',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactus',
            name='mobile',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
