# Generated by Django 2.1.7 on 2019-06-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190621_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, help_text='Please enter your name...', max_length=100),
        ),
    ]
