# Generated by Django 2.1.7 on 2019-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190621_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('size1', models.DecimalField(decimal_places=0, max_digits=10)),
                ('size2', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
