# Generated by Django 2.1.7 on 2019-04-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='One_side',
            new_name='user_upload',
        ),
    ]
