# Generated by Django 2.1.7 on 2019-06-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0002_auto_20190420_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_upload',
            name='image',
        ),
    ]
