# Generated by Django 2.1.7 on 2019-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_side',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
