# Generated by Django 2.1.7 on 2019-04-14 06:47

from django.db import migrations, models
import django.utils.timezone
import visitinglinks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0002_one_side_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_side',
            name='filepath',
            field=models.FileField(default=django.utils.timezone.now, upload_to='orders/%Y/%m/%d/', validators=[visitinglinks.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
