# Generated by Django 2.1.7 on 2019-04-14 07:16

from django.db import migrations, models
import visitinglinks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0003_one_side_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_side',
            name='filepath',
            field=models.FileField(upload_to='orders/', validators=[visitinglinks.validators.validate_file_size]),
        ),
    ]
