# Generated by Django 2.1.7 on 2019-04-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0004_auto_20190414_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='one_side',
            old_name='filepath',
            new_name='myfile',
        ),
    ]
