# Generated by Django 2.1.7 on 2019-04-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0005_auto_20190414_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='One_side',
        ),
    ]
