# Generated by Django 2.1.7 on 2019-04-15 06:02

from django.db import migrations, models
import visitinglinks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitinglinks', '0006_delete_one_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='One_side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='orders/', validators=[visitinglinks.validators.validate_file_size])),
            ],
        ),
    ]
