# Generated by Django 2.1.7 on 2019-04-20 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0007_one_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_side',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='one_side',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='one_side',
            name='size1',
            field=models.DecimalField(decimal_places=0, default=89, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='one_side',
            name='size2',
            field=models.DecimalField(decimal_places=0, default=51, max_digits=10),
            preserve_default=False,
        ),
    ]
