# Generated by Django 2.1.7 on 2019-04-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0008_auto_20190420_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='one_side',
            name='myfile',
        ),
    ]
