# Generated by Django 2.1.7 on 2019-04-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitinglinks', '0009_remove_one_side_myfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='One_side',
        ),
    ]
